supabase_url = "https://ypdtrkvebwjiqlmryaoc.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZHRya3ZlYndqaXFsbXJ5YW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNTIzNjEsImV4cCI6MjA3NjgyODM2MX0.cWzJQ59oY8xgZvBJ0I7a1a4XWXkRfeIdHbC3PSzVG4w"
